name: .NET CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    strategy:
      matrix:
        build-config: [ Debug, Release ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ matrix.build-config }} --no-restore
    - name: Test
      run: dotnet test --configuration ${{ matrix.build-config }} --no-restore --verbosity normal ./test/test.csproj
